version: "3.8"

services:
  app:
    build: .
    container_name: chat_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["python", "main.py"]

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
