name: Automatic Tagging
on:
  push:
    branches:
      - master
      - dev/*

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --local user.email "githubactions"
          git config --local user.name "githubactions"
      - name: Create tag
        run: |
          TAG_NAME="$(date +'%Y%m%d%H%M%S')-$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)"
          git tag -a "$TAG_NAME" -m "Automatic tag for push from $(git rev-parse --abbrev-ref HEAD)"
          git push origin --tags
