name: Automatic Tagging
on:
  push:
    branches:
      - master
      - dev/*

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --local user.email "githubactions"
          git config --local user.name "githubactions"
      - name: Create tag
        run: |
          git tag -a "v$(git rev-parse --short HEAD)" -m "Automatic tag for push"
          git push origin --tags
